// Self-test for src/network/zano_stratum_protocol.{hpp,cpp} - no sockets,
// no live daemon required. Validates:
//   1. Hex encode/decode against hand-computed expected strings.
//   2. Encode/decode round-trips.
//   3. Request builders produce well-formed, correctly-shaped JSON.
//   4. The response parser against a message shaped exactly like
//      zanod's real get_work_json() output (hand-written literal, not
//      generated by our own encoder, so this actually exercises the
//      parser against independently-constructed wire data).
//   5. MessageFramer against split/concatenated buffers.
#include <cstdio>
#include <cstring>

#include <nlohmann/json.hpp>

#include "../../src/network/zano_stratum_protocol.hpp"

using namespace deepcore::network::zano_stratum;
using nlohmann::json;

namespace {

int g_failures = 0;

void check(bool cond, const char* what)
{
    if (cond)
    {
        std::printf("PASS: %s\n", what);
    }
    else
    {
        std::printf("FAIL: %s\n", what);
        ++g_failures;
    }
}

void check_eq_str(const std::string& actual, const std::string& expected, const char* what)
{
    if (actual == expected)
    {
        std::printf("PASS: %s\n", what);
    }
    else
    {
        std::printf("FAIL: %s\n  expected: %s\n  actual  : %s\n", what, expected.c_str(), actual.c_str());
        ++g_failures;
    }
}

}  // namespace

int main()
{
    // ---- 1. Hex encode: hand-computed expected values ----
    {
        uint8_t pattern[4] = {0x00, 0x01, 0x0a, 0xff};
        check_eq_str(hex_encode(pattern, 4), "0x00010aff", "hex_encode straight order");
        check_eq_str(hex_encode_reversed(pattern, 4), "0xff0a0100", "hex_encode_reversed reverses byte order");
    }

    // ---- 2. Decode round-trips, including case-insensitive input ----
    {
        uint8_t original[8] = {0xde, 0xad, 0xbe, 0xef, 0x12, 0x34, 0x56, 0x78};
        std::string enc = hex_encode(original, 8);
        uint8_t decoded[8] = {};
        check(hex_decode(enc, decoded, 8) && std::memcmp(original, decoded, 8) == 0, "hex_decode round-trips hex_encode output");

        std::string enc_rev = hex_encode_reversed(original, 8);
        uint8_t decoded_rev[8] = {};
        check(hex_decode_reversed(enc_rev, decoded_rev, 8) && std::memcmp(original, decoded_rev, 8) == 0,
            "hex_decode_reversed round-trips hex_encode_reversed output");

        // Uppercase hex must still parse (matches hexmap_backward accepting A-F and a-f).
        uint8_t upper_decoded[4] = {};
        check(hex_decode("0xDEADBEEF", upper_decoded, 4) &&
                  upper_decoded[0] == 0xde && upper_decoded[1] == 0xad && upper_decoded[2] == 0xbe && upper_decoded[3] == 0xef,
            "hex_decode accepts uppercase hex digits");

        // Wrong length and invalid characters must fail, not silently truncate/garbage-decode.
        uint8_t dummy[4] = {};
        check(!hex_decode("0x1234", dummy, 4), "hex_decode rejects wrong length");
        check(!hex_decode("0xzzzzzzzz", dummy, 4), "hex_decode rejects non-hex characters");
    }

    // ---- 3. u64 reversed hex round-trip (nonce/hashrate encoding path) ----
    // Cross-checked by hand against pod_from_net_format_reverse's algorithm
    // in this conversation before writing the implementation - see
    // zano_stratum_protocol.cpp's u64_to_bytes8_native comment.
    {
        uint64_t nonce = 0x123456789abcdef0ULL;
        std::array<uint8_t, 32> zero_hash{};
        std::string req = build_submit_work(42, "testworker", nonce, zero_hash, zero_hash);
        json j = json::parse(req);
        std::string nonce_hex = j["params"][0].get<std::string>();
        check_eq_str(nonce_hex, "0x123456789abcdef0", "build_submit_work encodes nonce in big-endian-style reversed hex");
    }

    // ---- 4. Request builders: well-formed JSON with expected shape ----
    {
        std::string req = build_get_work(7);
        check(req.size() > 0 && req.back() == '\n', "build_get_work is newline-terminated");
        json j = json::parse(req);  // throws (test fails loudly) if malformed
        check(j["id"].get<int64_t>() == 7 && j["method"] == "eth_getWork" && j["jsonrpc"] == "2.0" && j["params"].empty(),
            "build_get_work has correct id/method/jsonrpc/empty params");
    }
    {
        std::string req = build_submit_login(1, "ZxTestAddress", "x", "rig1");
        json j = json::parse(req);
        check(j["method"] == "eth_submitLogin" && j["params"][0] == "ZxTestAddress" && j["params"][1] == "x" && j["worker"] == "rig1",
            "build_submit_login places user/pass in params, worker as top-level field");
    }
    {
        std::array<uint8_t, 32> rate_id{};
        rate_id[0] = 0xaa;
        std::string req = build_submit_hashrate(3, 123456789ULL, rate_id);
        json j = json::parse(req);
        check(j["method"] == "eth_submitHashrate" && j["params"].is_array() && j["params"].size() == 2,
            "build_submit_hashrate has 2-element params array");
    }

    // ---- 5. Parser against a hand-written literal matching zanod's real
    //         get_work_json() shape (independently constructed, not via
    //         our own encoder, so this actually validates the parser
    //         against the real wire format rather than testing our own
    //         code against itself). ----
    {
        // pow_hash = 32 bytes of 0x11, seed_hash = 32 bytes of 0x22,
        // target_boundary bytes 0x00..0x1f (reversed on the wire),
        // height = 12345 (reversed on the wire).
        std::string pow_hash_hex = "0x" + std::string(64, '1');
        std::string seed_hash_hex = "0x" + std::string(64, '2');
        // target_boundary bytes are 0x00,0x01,...,0x1f; reversed-encoded
        // means the wire string lists them from byte[31] down to byte[0].
        std::string target_hex = "0x1f1e1d1c1b1a191817161514131211100f0e0d0c0b0a09080706050403020100";
        // height = 12345 = 0x3039, as 8 bytes reversed-encoded ->
        // "0x0000000000003039".
        std::string height_hex = "0x0000000000003039";

        std::string literal = "{\"jsonrpc\":\"2.0\",\"id\":9,\"result\":[\"" + pow_hash_hex + "\",\"" +
            seed_hash_hex + "\",\"" + target_hex + "\",\"" + height_hex + "\"]}";

        auto parsed = parse_message(literal);
        check(parsed.has_value() && parsed->kind == MessageKind::Work, "parses a real-shaped eth_getWork response as Work");
        if (parsed && parsed->kind == MessageKind::Work)
        {
            check(parsed->id.has_value() && *parsed->id == 9, "parsed work response carries correct id");
            bool pow_ok = true, seed_ok = true, target_ok = true;
            for (int i = 0; i < 32; ++i)
            {
                if (parsed->work.pow_hash[i] != 0x11) pow_ok = false;
                if (parsed->work.seed_hash[i] != 0x22) seed_ok = false;
                if (parsed->work.target_boundary[i] != static_cast<uint8_t>(i)) target_ok = false;
            }
            check(pow_ok, "parsed pow_hash bytes correct (straight decode)");
            check(seed_ok, "parsed seed_hash bytes correct (straight decode)");
            check(target_ok, "parsed target_boundary bytes correct (reversed decode undoes wire reversal)");
            check(parsed->work.height == 12345, "parsed height correct (reversed decode)");
        }
    }

    // ---- 6. Ok and Error response shapes ----
    {
        auto ok = parse_message(R"({"jsonrpc":"2.0","id":5,"result":true})");
        check(ok.has_value() && ok->kind == MessageKind::Ok && ok->id == 5, "parses result:true as Ok");

        auto err = parse_message(R"({"jsonrpc":"2.0","id":6,"error":{"code":-32000,"message":"not enough work was done"}})");
        check(err.has_value() && err->kind == MessageKind::Error && err->error_code == -32000 &&
                  err->error_message == "not enough work was done",
            "parses a real-shaped error response");

        auto garbage = parse_message("not json at all {");
        check(!garbage.has_value(), "malformed JSON returns nullopt, does not throw/crash");
    }

    // ---- 7. MessageFramer: brace-counted extraction, including a message
    //         split across two feed() calls (simulating a partial TCP read). ----
    {
        MessageFramer framer;
        std::string obj1 = R"({"a":1})";
        std::string obj2 = R"({"b":{"nested":2}})";
        framer.feed(obj1 + obj2);

        std::string out;
        check(framer.pop_object(out) && out == obj1, "framer extracts first back-to-back object");
        check(framer.pop_object(out) && out == obj2, "framer extracts second back-to-back object (handles nested braces)");
        check(!framer.pop_object(out), "framer has nothing left after both objects popped");

        // Now split a single object across two feed() calls.
        MessageFramer framer2;
        std::string whole = R"({"split":"message"})";
        framer2.feed(whole.substr(0, 5));
        check(!framer2.pop_object(out), "framer yields nothing on a partial object");
        framer2.feed(whole.substr(5));
        check(framer2.pop_object(out) && out == whole, "framer completes and extracts object once the rest arrives");
    }

    if (g_failures == 0)
    {
        std::printf("\nALL CHECKS PASSED: zano_stratum_protocol matches zanod's real wire format.\n");
        return 0;
    }
    std::printf("\n%d CHECK(S) FAILED.\n", g_failures);
    return 1;
}
