// Implementation of deepcore::progpowz::NvrtcWarpSearcher - see
// progpowz_nvrtc_kernel.hpp for scope/status (short version: written,
// NOT YET COMPILED OR RUN - no CUDA toolkit is available in the
// environment this was written in, see src/cuda/README.md).
//
// Plain host C++ (not a .cu file): cuda.h/nvrtc.h/cuda_runtime.h are all
// ordinary C headers usable from any C++ compiler - only actual
// __global__/__device__ kernel code needs nvcc, and this file contains
// none (the kernel it compiles and launches exists only as a runtime-
// generated string - see progpowz_codegen.hpp). Compiled with the
// project's normal host compiler and linked against libcudart (already
// used elsewhere), libcuda (the driver stub - always installed alongside
// any CUDA toolkit, distinct from the kernel-mode driver), and libnvrtc.
//
// Mixes the CUDA Runtime API (cudaMalloc/cudaMemcpy/cudaFree, for output
// buffer management - reusing what the rest of the project already uses
// rather than introducing cuMemAlloc/cuMemcpyDtoH as a second way to do
// the same thing) with the Driver API (cuModuleLoadDataEx/cuLaunchKernel,
// the only way to load and launch a module compiled at runtime via
// NVRTC). This interop is standard, documented CUDA usage:
// cuDevicePrimaryCtxRetain() below attaches to the exact same per-device
// "primary context" the Runtime API already implicitly creates and uses,
// so cudaMalloc'd memory and cuLaunchKernel'd kernels share one context.

#include "progpowz_nvrtc_kernel.hpp"

#include <cstdio>
#include <cstring>

#include <cuda.h>
#include <cuda_runtime.h>
#include <nvrtc.h>

#include "progpowz_codegen.hpp"

namespace deepcore::progpowz {

namespace {

// Auto-generated by CMakeLists.txt (at CONFIGURE time - see that file's
// "Embed progpowz_portable.hpp for NVRTC" comment) from the real
// src/cuda/progpowz_portable.hpp, as a byte array (not a string literal -
// avoids any quoting/escaping risk for arbitrary file content). Defines
// `kEmbeddedProgpowzPortableHeaderBytes`. NOTE: this is regenerated on
// `cmake -S . -B build` (reconfigure), NOT on a plain `cmake --build
// build` - if progpowz_portable.hpp changes, reconfigure before trusting
// a build of NVRTC-related targets.
#include "progpowz_portable_hpp_embedded.inc"

const char* const kEmbeddedProgpowzPortableHeader =
    reinterpret_cast<const char*>(kEmbeddedProgpowzPortableHeaderBytes);

// NVRTC's bundled standard-header support is limited and version-
// dependent (real-world reports of <cstdint>/<cstring> availability
// under NVRTC are inconsistent across CUDA versions - see
// src/cuda/README.md's sourced research). progpowz_portable.hpp needs
// only a handful of fixed-width typedefs, `size_t`, and `std::memcpy`
// (used by calculate_dataset_item_2048 - dead code for this kernel's
// actual call path, but still semantically parsed since it's a
// non-template inline function) - supplying minimal, guaranteed-correct
// stubs for these two header names removes the dependency on NVRTC's
// bundled-header behavior entirely, rather than gambling on it.
const char* const kStubCstdintHeader =
    "#pragma once\n"
    "typedef signed char int8_t;\n"
    "typedef unsigned char uint8_t;\n"
    "typedef short int16_t;\n"
    "typedef unsigned short uint16_t;\n"
    "typedef int int32_t;\n"
    "typedef unsigned int uint32_t;\n"
    "typedef long long int64_t;\n"
    "typedef unsigned long long uint64_t;\n";

const char* const kStubCstringHeader =
    "#pragma once\n"
    "namespace std {\n"
    "inline __device__ void* memcpy(void* dst, const void* src, unsigned long long n)\n"
    "{\n"
    "    unsigned char* d = (unsigned char*)dst;\n"
    "    const unsigned char* s = (const unsigned char*)src;\n"
    "    for (unsigned long long i = 0; i < n; ++i) d[i] = s[i];\n"
    "    return dst;\n"
    "}\n"
    "}  // namespace std\n";

// Same env-var-tunable pattern as progpowz_kernel.cu's
// warp_kernel_threads_per_block() (intentionally duplicated in this small
// form rather than shared across the nvcc-compiled and plain-C++-compiled
// halves of the project - not worth a shared header for five lines).
// This kernel's real register usage will differ from the interpreted
// warp kernel's (no dst_seq/src_seq arrays at all), so the optimal value
// here may not be identical - worth its own sweep once this path is
// validated on real hardware.
uint32_t nvrtc_kernel_threads_per_block()
{
    static const uint32_t value = [] {
        const uint32_t default_value = 256;
        const char* env = std::getenv("DEEPCORE_NVRTC_THREADS_PER_BLOCK");
        if (!env) return default_value;
        char* end = nullptr;
        long parsed = std::strtol(env, &end, 10);
        if (end == env || *end != '\0' || parsed <= 0 || parsed % 32 != 0)
        {
            std::fprintf(stderr,
                "warning: DEEPCORE_NVRTC_THREADS_PER_BLOCK=\"%s\" is invalid (must be a positive "
                "multiple of 32) - using default %u\n",
                env, default_value);
            return default_value;
        }
        return static_cast<uint32_t>(parsed);
    }();
    return value;
}

}  // namespace

struct NvrtcWarpSearcher::Impl
{
    int device_index = 0;
    bool cuda_initialized = false;
    CUdevice cu_device{};
    CUcontext cu_context{};

    int cached_period = -1;
    CUmodule cu_module{};
    CUfunction cu_function{};

    ~Impl()
    {
        if (cached_period >= 0)
            cuModuleUnload(cu_module);
        if (cuda_initialized)
            cuDevicePrimaryCtxRelease(cu_device);
    }
};

NvrtcWarpSearcher::NvrtcWarpSearcher(int device_index) : impl_(std::make_unique<Impl>())
{
    impl_->device_index = device_index;
}

NvrtcWarpSearcher::~NvrtcWarpSearcher() = default;

bool NvrtcWarpSearcher::search(const void* device_l1_cache_words, uint32_t full_dataset_num_items,
    const void* device_full_dataset, int block_number, const hash256& header_hash, uint64_t start_nonce,
    uint32_t count, std::vector<GpuHashResult>& out_results, std::string& error)
{
    error.clear();
    Impl& s = *impl_;

    if (!s.cuda_initialized)
    {
        CUresult rc = cuInit(0);
        if (rc != CUDA_SUCCESS) { error = "cuInit failed"; return false; }
        rc = cuDeviceGet(&s.cu_device, s.device_index);
        if (rc != CUDA_SUCCESS) { error = "cuDeviceGet failed"; return false; }
        rc = cuDevicePrimaryCtxRetain(&s.cu_context, s.cu_device);
        if (rc != CUDA_SUCCESS) { error = "cuDevicePrimaryCtxRetain failed"; return false; }
        s.cuda_initialized = true;
    }
    cuCtxSetCurrent(s.cu_context);

    const int period = block_number / period_length;
    if (period != s.cached_period)
    {
        if (s.cached_period >= 0)
        {
            cuModuleUnload(s.cu_module);
            s.cached_period = -1;
        }

        const std::string source = generate_progpowz_nvrtc_kernel_source(block_number);

        nvrtcProgram prog{};
        const char* header_names[] = {"progpowz_portable.hpp", "cstdint", "cstring"};
        const char* header_sources[] = {kEmbeddedProgpowzPortableHeader, kStubCstdintHeader, kStubCstringHeader};
        nvrtcResult nrc = nvrtcCreateProgram(
            &prog, source.c_str(), "progpowz_nvrtc_kernel.cu", 3, header_sources, header_names);
        if (nrc != NVRTC_SUCCESS)
        {
            error = std::string("nvrtcCreateProgram failed: ") + nvrtcGetErrorString(nrc);
            return false;
        }

        int major = 0, minor = 0;
        cuDeviceGetAttribute(&major, CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR, s.cu_device);
        cuDeviceGetAttribute(&minor, CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR, s.cu_device);
        char arch_opt[40];
        std::snprintf(arch_opt, sizeof(arch_opt), "--gpu-architecture=compute_%d%d", major, minor);
        const char* opts[] = {arch_opt};

        nrc = nvrtcCompileProgram(prog, 1, opts);

        size_t log_size = 0;
        nvrtcGetProgramLogSize(prog, &log_size);
        std::string log;
        if (log_size > 1)
        {
            log.resize(log_size);
            nvrtcGetProgramLog(prog, log.data());
        }
        if (!log.empty())
            std::fprintf(
                stderr, "NvrtcWarpSearcher: nvrtc compile log (period %d, arch %s):\n%s\n", period, arch_opt,
                log.c_str());

        if (nrc != NVRTC_SUCCESS)
        {
            error = std::string("nvrtcCompileProgram failed: ") + nvrtcGetErrorString(nrc) +
                (log.empty() ? "" : ("\n" + log));
            nvrtcDestroyProgram(&prog);
            return false;
        }

        size_t ptx_size = 0;
        nvrtcGetPTXSize(prog, &ptx_size);
        std::vector<char> ptx(ptx_size);
        nvrtcGetPTX(prog, ptx.data());
        nvrtcDestroyProgram(&prog);

        CUresult crc = cuModuleLoadDataEx(&s.cu_module, ptx.data(), 0, nullptr, nullptr);
        if (crc != CUDA_SUCCESS)
        {
            error = "cuModuleLoadDataEx failed (see stderr nvrtc log above for the PTX that failed to load)";
            return false;
        }

        crc = cuModuleGetFunction(&s.cu_function, s.cu_module, "progpowz_nvrtc_warp_kernel");
        if (crc != CUDA_SUCCESS)
        {
            cuModuleUnload(s.cu_module);
            error = "cuModuleGetFunction failed - \"progpowz_nvrtc_warp_kernel\" symbol not found "
                    "(check the extern \"C\" declaration in generate_progpowz_nvrtc_kernel_source())";
            return false;
        }

        s.cached_period = period;
    }

    const uint32_t threads_per_block = nvrtc_kernel_threads_per_block();
    const uint32_t total_threads = count * static_cast<uint32_t>(num_lanes);
    const uint32_t blocks = (total_threads + threads_per_block - 1) / threads_per_block;

    void* d_out = nullptr;
    const size_t out_bytes = static_cast<size_t>(count) * sizeof(GpuHashResult);
    if (cudaMalloc(&d_out, out_bytes) != cudaSuccess)
    {
        error = "cudaMalloc failed for output buffer";
        return false;
    }

    uint32_t local_full_dataset_num_items = full_dataset_num_items;
    hash256 local_header = header_hash;
    uint64_t local_start_nonce = start_nonce;
    uint32_t local_count = count;

    void* kernel_params[] = {(void*)&device_l1_cache_words, (void*)&local_full_dataset_num_items,
        (void*)&device_full_dataset, (void*)&local_header, (void*)&local_start_nonce, (void*)&local_count,
        (void*)&d_out};

    CUresult lrc = cuLaunchKernel(s.cu_function, blocks, 1, 1, threads_per_block, 1, 1,
        /*sharedMemBytes=*/0, /*stream=*/nullptr, kernel_params, nullptr);
    if (lrc != CUDA_SUCCESS)
    {
        cudaFree(d_out);
        error = "cuLaunchKernel failed";
        return false;
    }

    if (cudaDeviceSynchronize() != cudaSuccess)
    {
        cudaFree(d_out);
        error = "device sync failed after NVRTC kernel launch";
        return false;
    }

    out_results.resize(count);
    cudaError_t mrc = cudaMemcpy(out_results.data(), d_out, out_bytes, cudaMemcpyDeviceToHost);
    cudaFree(d_out);
    if (mrc != cudaSuccess)
    {
        error = "cudaMemcpy (device to host) failed for output buffer";
        return false;
    }

    return true;
}

}  // namespace deepcore::progpowz
